general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
    inhibit_sleep = 2
}

# Dim screen / lower brightness after a while 
listener {
    timeout = 150
    on-timeout = brightnessctl set 10%        # reduce backlight
    on-resume = brightnessctl restore         # restore brightness
}

# Lock screen after 5 min idle
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn off screen after 5.5 min idle
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
    on-resume = hyprctl dispatch dpms on && brightnessctl restore
}

# Suspend after 30 min idle 
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}

# Clear clipboard on lock
# listener {
#     timeout = 300
#     on-timeout = loginctl lock-session && echo -n "" | wl-copy
# }
