# Prefix
set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

# --- Basic Settings ---
# set -ga update-environment TERM
# set -ga update-environment TERM_PROGRAM
set -g mouse on
set -g renumber-windows on           # Automatically updates window indices
set-option -g allow-rename on        # Rename windows automatically
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc,tmux-256color:Tc"

# Imae rendering in yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# --- Keybindings ---
bind r source-file ~/.tmux.conf \; display-message "Reloaded ~/.tmux.conf"
bind q kill-pane                     # Kill pane
bind n new-window -c "#{pane_current_path}"

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-style pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Split panes (preserve cwd)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vi-copy mode
setw -g mode-keys vi
bind [ copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"

# Window navigation (Ctrl-h/l)
bind -n C-h previous-window
bind -n C-l next-window

# --- TPM Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'thepante/tmux-git-autofetch'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# Catppuccin Theme Settings
# set -g @catppuccin_flavor 'mocha'
# set -g @catppuccin_window_status_style "rounded"
# set -g @catppuccin_directory_text "#{pane_current_path}"
# set -g @catppuccin_window_current_text "#{window_name}"
# set -g @catppuccin_window_default_text "#{window_name}"
# set -g @catppuccin_window_default_fill "number"
# set -g @catppuccin_status_modules_right "directory user host"
# set -g @catppuccin_status_modules_left "session"
# set -g @catppuccin_status_fill "all"
# set -g @catppuccin_status_connect_separator "yes"
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_number_position 'right'
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_default_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text '#W'
set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'
set -g @catppuccin_date_time_text '%d.%m. %H:%M'
set -g @catppuccin_status_module_text_bg '#{E:@thm_mantle}'

# Status Bar Plugins
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g allow-rename off
set -g status-position bottom
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
set -g status-left '#{E:@catppuccin_status_session} '
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right '#{E:@catppuccin_status_cpu}'
set -ag status-right '#{E:@catppuccin_status_uptime}'
set -ag status-right '#{E:@catppuccin_status_gitmux}'

# --- Initialize TMUX Plugin Manager (must be last) ---
run '~/.tmux/plugins/tpm/tpm'
