# only this line might not be enough
set -g default-terminal "xterm-256color"

# Allowing yazi to use windows terminal image rendering
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# Allow mouse
set -g mouse on

# Sane scrolling
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
# bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"

# Needs this line also to overrides the default color
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Automatically updates window's index
set -g renumber-windows on

# kill window
bind q killp

# open new window in current directory
bind n new-window -c "#{pane_current_path}"

# Use vim-like pane switching with Ctrl+B + h/j/k/l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Optional: Enable faster pane resizing using the same keys with the prefix + Shift
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R

# don't rename windows automatically
set-option -g allow-rename off

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# Enable vi-style keys in copy mode
setw -g mode-keys vi

# Remap copy mode to Ctrl+B + [ 
bind [ copy-mode

# Use 'y' to copy in copy mode
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"

# Navigate between windows
bind -n C-h previous-window
bind -n C-l next-window

# Split panes
bind | split-window -h  
bind - split-window -v  

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'

# catppuccin
set -g @plugin 'catppuccin/tmux#v2.0.0' # See https://github.com/catppuccin/tmux/tags for additional tags
# ...alongside
set -g @plugin 'tmux-plugins/tpm'
set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha
# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.config/tmux/plugins/tmux/catppuccin.tmux`
run ~/.config/tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# which-key
set -g @plugin 'alexwforsythe/tmux-which-key'

run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
